const generateReadme = (answers) => {
    return `
    
<h1 align='center'>${answers.projectTitle}</h1>

![badge](https://img.shields.io/badge/license-${answers.license}-yellow)

## Description

>🔍 ${answers.description}

## Table of Contents

- [Installation](#installation)
- [Usage](#usage)
- [License](#license)
- [Contributing](#contributing)
- [Tests](#tests)
- [Contact](#contact)

## Installation

>💾 ${answers.installation}

## Usage

>💻 ${answers.usage}

## License

![badge](https://img.shields.io/badge/license-${answers.license}-yellow)

>This application is covered by ${answers.license} license.

## Contributing

>👪 ${answers.contributing}

## Tests

>✏️ ${answers.tests}

## Contact
>Find me on GitHub: [${answers.username}](https://github.com/${answers.username})
>
>✉️ Alternatively, email me with any questions at ${answers.email}.

<br></br>
_This README was generated by [README-Generator](https://github.com/BlakeGeo/README-Generator)_

`
}

module.exports = generateReadme;